In [ ]:
import pandas as pd

Upload dataset

In [ ]:
df = pd.read_csv(r"/content/Supermarket sales and operational analysis_unclean.csv")
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Quantity,Discount,Profit,Order Priority,Shipping Cost,Customer Tenure,Marketing Channel,Product Rating,Return Status,Payment Method
0,1,CA-2016-101623,2/28/2016,3/6/2016,Standard Class,RR-19525,Rick Reed,CORPORATE,United States,New York City,...,6,0.0,18.2400,Medium,5.45,Returning,NaN,1.0,No,Credit Card
1,2,CA-2017-154410,10/21/2017,10/24/2017,First Class,MD-17860,Michael Dominguez,Corporate,United States,Indianapolis,...,8,0.0,9.0912,High,90.10,New,Social Media,4.0,No,Credit Card
2,3,CA-2017-127306,1/14/2017,1/18/2017,Standard Class,BH-11710,Brosina Hoffman,consumer,United States,Johnson City,...,2,0.7,-1.8392,High,0.27,New,Referral,4.0,Yes,Net Banking
3,4,CA-2016-126102,9/10/2016,9/12/2016,Second Class,DV-13465,Dianna Vittorini,consumer,United States,Los Angeles,...,2,0.2,89.9548,Low,19.00,Returning,Direct,1.0,No,Credit Card
4,5,CA-2016-101336,11/13/2016,11/18/2016,Standard Class,CK-12760,Cyma Kinney,Corporate,United States,New York City,...,3,0.0,9.8901,Low,4.76,Returning,Ads,2.0,No,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100295,22973,US-2016-103646,4/21/2016,4/26/2016,Standard Class,SP-20545,Sibella Parks,CORPORATE,United States,Chicago,...,3,0.8,-126.8592,Low,5.24,Returning,Ads,3.0,No,Cash on Delivery
100296,60743,CA-2017-168389,12/11/2017,12/17/2017,Standard Class,DV-13045,Darrin Van Huff,Corporate,United States,Jacksonville,...,1,0.2,1.3584,Critical,0.99,Returning,Direct,3.0,No,UPI
100297,13969,US-2015-163433,4/18/2015,4/22/2015,Second Class,MP-17965,Michael Paige,Corporate,United States,Mcallen,...,4,0.2,24.4768,NaN,34.41,Returning,Direct,4.0,No,Credit Card
100298,49795,US-2016-139262,2/21/2016,2/25/2016,Standard Class,LC-16960,Lindsay Castell,Home Office,United States,Tampa,...,3,0.2,32.4342,Critical,48.49,Returning,Ads,4.0,No,Credit Card
100299,33761,CA-2016-164938,2/11/2016,2/13/2016,First Class,PB-19210,Phillip Breyer,Corporate,United States,Tulsa,...,7,0.0,0.6993,Medium,10.08,New,Referral,4.0,No,Credit Card

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Quantity,Discount,Profit,Order Priority,Shipping Cost,Customer Tenure,Marketing Channel,Product Rating,Return Status,Payment Method
0,1,CA-2016-101623,2/28/2016,3/6/2016,Standard Class,RR-19525,Rick Reed,CORPORATE,United States,New York City,...,6,0.0,18.2400,Medium,5.45,Returning,NaN,1.0,No,Credit Card
1,2,CA-2017-154410,10/21/2017,10/24/2017,First Class,MD-17860,Michael Dominguez,Corporate,United States,Indianapolis,...,8,0.0,9.0912,High,90.10,New,Social Media,4.0,No,Credit Card
2,3,CA-2017-127306,1/14/2017,1/18/2017,Standard Class,BH-11710,Brosina Hoffman,consumer,United States,Johnson City,...,2,0.7,-1.8392,High,0.27,New,Referral,4.0,Yes,Net Banking
3,4,CA-2016-126102,9/10/2016,9/12/2016,Second Class,DV-13465,Dianna Vittorini,consumer,United States,Los Angeles,...,2,0.2,89.9548,Low,19.00,Returning,Direct,1.0,No,Credit Card
4,5,CA-2016-101336,11/13/2016,11/18/2016,Standard Class,CK-12760,Cyma Kinney,Corporate,United States,New York City,...,3,0.0,9.8901,Low,4.76,Returning,Ads,2.0,No,UPI

In [ ]:
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Quantity,Discount,Profit,Order Priority,Shipping Cost,Customer Tenure,Marketing Channel,Product Rating,Return Status,Payment Method
100295,22973,US-2016-103646,4/21/2016,4/26/2016,Standard Class,SP-20545,Sibella Parks,CORPORATE,United States,Chicago,...,3,0.8,-126.8592,Low,5.24,Returning,Ads,3.0,No,Cash on Delivery
100296,60743,CA-2017-168389,12/11/2017,12/17/2017,Standard Class,DV-13045,Darrin Van Huff,Corporate,United States,Jacksonville,...,1,0.2,1.3584,Critical,0.99,Returning,Direct,3.0,No,UPI
100297,13969,US-2015-163433,4/18/2015,4/22/2015,Second Class,MP-17965,Michael Paige,Corporate,United States,Mcallen,...,4,0.2,24.4768,NaN,34.41,Returning,Direct,4.0,No,Credit Card
100298,49795,US-2016-139262,2/21/2016,2/25/2016,Standard Class,LC-16960,Lindsay Castell,Home Office,United States,Tampa,...,3,0.2,32.4342,Critical,48.49,Returning,Ads,4.0,No,Credit Card
100299,33761,CA-2016-164938,2/11/2016,2/13/2016,First Class,PB-19210,Phillip Breyer,Corporate,United States,Tulsa,...,7,0.0,0.6993,Medium,10.08,New,Referral,4.0,No,Credit Card

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100300 entries, 0 to 100299
Data columns (total 28 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Row ID             100300 non-null  int64
 1   Order ID           100300 non-null  object
 2   Order Date         100300 non-null  object
 3   Ship Date          100300 non-null  object
 4   Ship Mode          100300 non-null  object
 5   Customer ID        100300 non-null  object
 6   Customer Name      100300 non-null  object
 7   Segment            100300 non-null  object
 8   Country            100300 non-null  object
 9   City               100300 non-null  object
 10  State              100300 non-null  object
 11  Postal Code        100300 non-null  int64
 12  Region             100300 non-null  object
 13  Product ID         100300 non-null  object
 14  Category           100300 non-null  object
 15  Sub-Category       100300 non-null  object
 16  Product Name       100300 non-null  object
 17  Sales              100300 non-null  float64
 18  Quantity           100300 non-null  int64
 19  Discount           100300 non-null  float64
 20  Profit             100300 non-null  float64
 21  Order Priority     98292 non-null   object
 22  Shipping Cost      98294 non-null   float64
 23  Customer Tenure    100300 non-null  object
 24  Marketing Channel  98291 non-null   object
 25  Product Rating     98294 non-null   float64
 26  Return Status      100300 non-null  object
 27  Payment Method     100300 non-null  object
dtypes: float64(5), int64(3), object(20)
memory usage: 21.4+ MB

In [ ]:
df= df.drop(columns= 'Row ID')
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,...,Quantity,Discount,Profit,Order Priority,Shipping Cost,Customer Tenure,Marketing Channel,Product Rating,Return Status,Payment Method
0,CA-2016-101623,2/28/2016,3/6/2016,Standard Class,RR-19525,Rick Reed,CORPORATE,United States,New York City,New York,...,6,0.0,18.2400,Medium,5.45,Returning,NaN,1.0,No,Credit Card
1,CA-2017-154410,10/21/2017,10/24/2017,First Class,MD-17860,Michael Dominguez,Corporate,United States,Indianapolis,Indiana,...,8,0.0,9.0912,High,90.10,New,Social Media,4.0,No,Credit Card
2,CA-2017-127306,1/14/2017,1/18/2017,Standard Class,BH-11710,Brosina Hoffman,consumer,United States,Johnson City,Tennessee,...,2,0.7,-1.8392,High,0.27,New,Referral,4.0,Yes,Net Banking
3,CA-2016-126102,9/10/2016,9/12/2016,Second Class,DV-13465,Dianna Vittorini,consumer,United States,Los Angeles,California,...,2,0.2,89.9548,Low,19.00,Returning,Direct,1.0,No,Credit Card
4,CA-2016-101336,11/13/2016,11/18/2016,Standard Class,CK-12760,Cyma Kinney,Corporate,United States,New York City,New York,...,3,0.0,9.8901,Low,4.76,Returning,Ads,2.0,No,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100295,US-2016-103646,4/21/2016,4/26/2016,Standard Class,SP-20545,Sibella Parks,CORPORATE,United States,Chicago,Illinois,...,3,0.8,-126.8592,Low,5.24,Returning,Ads,3.0,No,Cash on Delivery
100296,CA-2017-168389,12/11/2017,12/17/2017,Standard Class,DV-13045,Darrin Van Huff,Corporate,United States,Jacksonville,Florida,...,1,0.2,1.3584,Critical,0.99,Returning,Direct,3.0,No,UPI
100297,US-2015-163433,4/18/2015,4/22/2015,Second Class,MP-17965,Michael Paige,Corporate,United States,Mcallen,Texas,...,4,0.2,24.4768,NaN,34.41,Returning,Direct,4.0,No,Credit Card
100298,US-2016-139262,2/21/2016,2/25/2016,Standard Class,LC-16960,Lindsay Castell,Home Office,United States,Tampa,Florida,...,3,0.2,32.4342,Critical,48.49,Returning,Ads,4.0,No,Credit Card
100299,CA-2016-164938,2/11/2016,2/13/2016,First Class,PB-19210,Phillip Breyer,Corporate,United States,Tulsa,Oklahoma,...,7,0.0,0.6993,Medium,10.08,New,Referral,4.0,No,Credit Card

In [ ]:
df['Order ID'].value_counts()[df['Order ID'].value_counts() > 1]

Order ID
CA-2017-100111    127
CA-2016-105732    126
CA-2016-165330    118
CA-2017-157987    115
US-2015-163433    101
                 ...
CA-2017-103968      3
CA-2017-156412      3
CA-2017-103877      2
CA-2017-157903      2
CA-2017-155705      2
Name: count, Length: 5007, dtype: int64

In [ ]:
df = df.drop_duplicates(subset=['Order ID'])
df['Order ID'].value_counts()[df['Order ID'].value_counts() > 1]

Series([], Name: count, dtype: int64)

In [ ]:
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,...,Quantity,Discount,Profit,Order Priority,Shipping Cost,Customer Tenure,Marketing Channel,Product Rating,Return Status,Payment Method
0,CA-2016-101623,2/28/2016,3/6/2016,Standard Class,RR-19525,Rick Reed,CORPORATE,United States,New York City,New York,...,6,0.0,18.2400,Medium,5.45,Returning,NaN,1.0,No,Credit Card
1,CA-2017-154410,10/21/2017,10/24/2017,First Class,MD-17860,Michael Dominguez,Corporate,United States,Indianapolis,Indiana,...,8,0.0,9.0912,High,90.10,New,Social Media,4.0,No,Credit Card
2,CA-2017-127306,1/14/2017,1/18/2017,Standard Class,BH-11710,Brosina Hoffman,consumer,United States,Johnson City,Tennessee,...,2,0.7,-1.8392,High,0.27,New,Referral,4.0,Yes,Net Banking
3,CA-2016-126102,9/10/2016,9/12/2016,Second Class,DV-13465,Dianna Vittorini,consumer,United States,Los Angeles,California,...,2,0.2,89.9548,Low,19.00,Returning,Direct,1.0,No,Credit Card
4,CA-2016-101336,11/13/2016,11/18/2016,Standard Class,CK-12760,Cyma Kinney,Corporate,United States,New York City,New York,...,3,0.0,9.8901,Low,4.76,Returning,Ads,2.0,No,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60553,CA-2017-108287,12/18/2017,12/20/2017,First Class,AG-10330,Alex Grayson,CONSUMER,United States,Charlotte,North Carolina,...,9,0.2,1.4256,High,1.08,Returning,Social Media,3.0,No,UPI
61371,CA-2015-153073,11/13/2015,11/13/2015,Same Day,HA-14905,Helen Abelman,CONSUMER,United States,Chicago,Illinois,...,9,0.6,-7.4358,Critical,2.15,Returning,Referral,4.0,No,Cash on Delivery
61863,US-2016-164189,3/24/2016,3/28/2016,Standard Class,DR-12880,Dan Reichenbach,Corporate,United States,Gresham,Oregon,...,4,0.2,25.1980,Critical,41.59,Returning,Ads,3.0,No,Net Banking
64212,CA-2016-127698,12/1/2016,12/1/2016,Same Day,MV-18190,Mike Vittorini,Consumer,United States,Raleigh,North Carolina,...,9,0.2,86.3928,Medium,123.31,Returning,Referral,2.0,Yes,UPI
68988,CA-2015-118423,3/24/2015,3/27/2015,First Class,DP-13390,Dennis Pardue,home office,United States,Peoria,Illinois,...,3,0.3,-35.9058,Low,33.39,New,Social Media,5.0,No,Credit Card

## **Null Value**

In [ ]:
Null_count = df.isnull().sum()
Null_count

Order ID               0
Order Date             0
Ship Date              0
Ship Mode              0
Customer ID            0
Customer Name          0
Segment                0
Country                0
City                   0
State                  0
Postal Code            0
Region                 0
Product ID             0
Category               0
Sub-Category           0
Product Name           0
Sales                  0
Quantity               0
Discount               0
Profit                 0
Order Priority       103
Shipping Cost        116
Customer Tenure        0
Marketing Channel    102
Product Rating       109
Return Status          0
Payment Method         0
dtype: int64

# **Product Rating Null Value Handing**

In [ ]:
df['Product Rating'].isnull().sum()

np.int64(109)

In [ ]:
df['Product Rating']= df.groupby(['Category','Sub-Category','Segment'])['Product Rating'].transform(
lambda x: x.fillna(x.mean())
)

<ipython-input-12-b21ac44cbca1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Product Rating']= df.groupby(['Category','Sub-Category','Segment'])['Product Rating'].transform(

In [ ]:
df['Product Rating'].isnull().sum()

np.int64(0)

## **Order Priority Missing Values**

In [ ]:
df['Order Priority'].isnull().sum()

np.int64(103)

In [ ]:
df['Order Priority']= df.groupby('Segment')['Order Priority'].transform(
lambda x: x.fillna(x.mode()[0])
)

<ipython-input-15-ba1bc0b9c4a2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Order Priority']= df.groupby('Segment')['Order Priority'].transform(

In [ ]:
df['Order Priority'].isnull().sum()

np.int64(0)

# **Shipping Cost Missing Value handling**

In [ ]:
df['Shipping Cost'].isnull().sum()

np.int64(116)

In [ ]:
df['Shipping Cost'] = df.groupby(['State','Ship Mode'])['Shipping Cost'].transform(
lambda x: x.fillna(x.median())
)

<ipython-input-18-d08fefe49b3a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Shipping Cost'] = df.groupby(['State','Ship Mode'])['Shipping Cost'].transform(

In [ ]:
df['Shipping Cost'].isnull().sum()

np.int64(0)

# **Marketing Channel missing value handling**

In [ ]:
df['Marketing Channel'].isnull().sum()

np.int64(102)

In [ ]:
df['Marketing Channel'] = df.groupby(['Segment', 'State','Category','Sub-Category'])['Marketing Channel'].transform(
    lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else 'Unknown')
)

<ipython-input-21-777526a76e5d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Marketing Channel'] = df.groupby(['Segment', 'State','Category','Sub-Category'])['Marketing Channel'].transform(

In [ ]:
df['Marketing Channel'].isnull().sum()

np.int64(0)

In [ ]:
check_null_value = df.isnull().sum()
check_null_value

Order ID             0
Order Date           0
Ship Date            0
Ship Mode            0
Customer ID          0
Customer Name        0
Segment              0
Country              0
City                 0
State                0
Postal Code          0
Region               0
Product ID           0
Category             0
Sub-Category         0
Product Name         0
Sales                0
Quantity             0
Discount             0
Profit               0
Order Priority       0
Shipping Cost        0
Customer Tenure      0
Marketing Channel    0
Product Rating       0
Return Status        0
Payment Method       0
dtype: int64

# **Fixing Appropriate Datatype for each Column**

In [ ]:
check_data_type = df.dtypes
check_data_type

Order ID              object
Order Date            object
Ship Date             object
Ship Mode             object
Customer ID           object
Customer Name         object
Segment               object
Country               object
City                  object
State                 object
Postal Code            int64
Region                object
Product ID            object
Category              object
Sub-Category          object
Product Name          object
Sales                float64
Quantity               int64
Discount             float64
Profit               float64
Order Priority        object
Shipping Cost        float64
Customer Tenure       object
Marketing Channel     object
Product Rating       float64
Return Status         object
Payment Method        object
dtype: object

In [ ]:
df['Order ID'] = df['Order ID'].astype(str)
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%m/%d/%Y')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%m/%d/%Y')
df['Ship Mode'] = df['Ship Mode'].astype(str)
df['Customer ID'] = df['Customer ID'].astype(str)
df['Customer Name'] = df['Customer Name'].astype(str)
df['Segment'] = df['Segment'].astype(str)
df['Country'] = df['Country'].astype('category')
df['City'] = df['City'].astype('category')
df['State'] = df['State'].astype('category')
df['Postal Code'] = df['Postal Code'].astype(str)
df['Region'] = df['Region'].astype('category')
df['Product ID'] = df['Product ID'].astype(str)
df['Product Name'] = df['Product Name'].astype(str)
df['Category'] = df['Category'].astype('category')
df['Sub-Category'] = df['Sub-Category'].astype('category')
df['Sales'] = df['Sales'].astype(float)
df['Quantity'] = df['Quantity'].astype(int)
df['Discount'] = df['Discount'].astype(float)
df['Profit'] = df['Profit'].astype(float)
df['Order Priority'] = df['Order Priority'].astype('category')
df['Payment Method'] = df['Payment Method'].astype('category')
df['Shipping Cost'] = df['Shipping Cost'].astype(float)
df['Customer Tenure'] = df['Customer Tenure'].astype(str)
df['Marketing Channel'] = df['Marketing Channel'].astype('category')
df['Product Rating'] = df['Product Rating'].astype(float)
df['Return Status'] = df['Return Status'].astype('category')
df

<ipython-input-25-0a7fc89dfee2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Order ID'] = df['Order ID'].astype(str)
<ipython-input-25-0a7fc89dfee2>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Order Date'] = pd.to_datetime(df['Order Date'], format='%m/%d/%Y')
<ipython-input-25-0a7fc89dfee2>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%m/%d/%Y')
<ipython-input-25-0a7fc89dfee2>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Ship Mode'] = df['Ship Mode'].astype(str)
<ipython-input-25-0a7fc89dfee2>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Customer ID'] = df['Customer ID'].astype(str)
<ipython-input-25-0a7fc89dfee2>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Customer Name'] = df['Customer Name'].astype(str)
<ipython-input-25-0a7fc89dfee2>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Segment'] = df['Segment'].astype(str)
<ipython-input-25-0a7fc89dfee2>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Country'] = df['Country'].astype('category')
<ipython-input-25-0a7fc89dfee2>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['City'] = df['City'].astype('category')
<ipython-input-25-0a7fc89dfee2>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['State'] = df['State'].astype('category')
<ipython-input-25-0a7fc89dfee2>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Postal Code'] = df['Postal Code'].astype(str)
<ipython-input-25-0a7fc89dfee2>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Region'] = df['Region'].astype('category')
<ipython-input-25-0a7fc89dfee2>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Product ID'] = df['Product ID'].astype(str)
<ipython-input-25-0a7fc89dfee2>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Product Name'] = df['Product Name'].astype(str)
<ipython-input-25-0a7fc89dfee2>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Category'] = df['Category'].astype('category')
<ipython-input-25-0a7fc89dfee2>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sub-Category'] = df['Sub-Category'].astype('category')
<ipython-input-25-0a7fc89dfee2>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sales'] = df['Sales'].astype(float)
<ipython-input-25-0a7fc89dfee2>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Quantity'] = df['Quantity'].astype(int)
<ipython-input-25-0a7fc89dfee2>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Discount'] = df['Discount'].astype(float)
<ipython-input-25-0a7fc89dfee2>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Profit'] = df['Profit'].astype(float)
<ipython-input-25-0a7fc89dfee2>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Order Priority'] = df['Order Priority'].astype('category')
<ipython-input-25-0a7fc89dfee2>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Payment Method'] = df['Payment Method'].astype('category')
<ipython-input-25-0a7fc89dfee2>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Shipping Cost'] = df['Shipping Cost'].astype(float)
<ipython-input-25-0a7fc89dfee2>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Customer Tenure'] = df['Customer Tenure'].astype(str)
<ipython-input-25-0a7fc89dfee2>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Marketing Channel'] = df['Marketing Channel'].astype('category')
<ipython-input-25-0a7fc89dfee2>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Product Rating'] = df['Product Rating'].astype(float)
<ipython-input-25-0a7fc89dfee2>:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Return Status'] = df['Return Status'].astype('category')

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,...,Quantity,Discount,Profit,Order Priority,Shipping Cost,Customer Tenure,Marketing Channel,Product Rating,Return Status,Payment Method
0,CA-2016-101623,2016-02-28,2016-03-06,Standard Class,RR-19525,Rick Reed,CORPORATE,United States,New York City,New York,...,6,0.0,18.2400,Medium,5.45,Returning,Referral,1.0,No,Credit Card
1,CA-2017-154410,2017-10-21,2017-10-24,First Class,MD-17860,Michael Dominguez,Corporate,United States,Indianapolis,Indiana,...,8,0.0,9.0912,High,90.10,New,Social Media,4.0,No,Credit Card
2,CA-2017-127306,2017-01-14,2017-01-18,Standard Class,BH-11710,Brosina Hoffman,consumer,United States,Johnson City,Tennessee,...,2,0.7,-1.8392,High,0.27,New,Referral,4.0,Yes,Net Banking
3,CA-2016-126102,2016-09-10,2016-09-12,Second Class,DV-13465,Dianna Vittorini,consumer,United States,Los Angeles,California,...,2,0.2,89.9548,Low,19.00,Returning,Direct,1.0,No,Credit Card
4,CA-2016-101336,2016-11-13,2016-11-18,Standard Class,CK-12760,Cyma Kinney,Corporate,United States,New York City,New York,...,3,0.0,9.8901,Low,4.76,Returning,Ads,2.0,No,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60553,CA-2017-108287,2017-12-18,2017-12-20,First Class,AG-10330,Alex Grayson,CONSUMER,United States,Charlotte,North Carolina,...,9,0.2,1.4256,High,1.08,Returning,Social Media,3.0,No,UPI
61371,CA-2015-153073,2015-11-13,2015-11-13,Same Day,HA-14905,Helen Abelman,CONSUMER,United States,Chicago,Illinois,...,9,0.6,-7.4358,Critical,2.15,Returning,Referral,4.0,No,Cash on Delivery
61863,US-2016-164189,2016-03-24,2016-03-28,Standard Class,DR-12880,Dan Reichenbach,Corporate,United States,Gresham,Oregon,...,4,0.2,25.1980,Critical,41.59,Returning,Ads,3.0,No,Net Banking
64212,CA-2016-127698,2016-12-01,2016-12-01,Same Day,MV-18190,Mike Vittorini,Consumer,United States,Raleigh,North Carolina,...,9,0.2,86.3928,Medium,123.31,Returning,Referral,2.0,Yes,UPI
68988,CA-2015-118423,2015-03-24,2015-03-27,First Class,DP-13390,Dennis Pardue,home office,United States,Peoria,Illinois,...,3,0.3,-35.9058,Low,33.39,New,Social Media,5.0,No,Credit Card

In [ ]:
check_data_type = df.dtypes
check_data_type

Order ID                     object
Order Date           datetime64[ns]
Ship Date            datetime64[ns]
Ship Mode                    object
Customer ID                  object
Customer Name                object
Segment                      object
Country                    category
City                       category
State                      category
Postal Code                  object
Region                     category
Product ID                   object
Category                   category
Sub-Category               category
Product Name                 object
Sales                       float64
Quantity                      int64
Discount                    float64
Profit                      float64
Order Priority             category
Shipping Cost               float64
Customer Tenure              object
Marketing Channel          category
Product Rating              float64
Return Status              category
Payment Method             category
dtype: object

### **Remove Unnecessary Spaces**

In [ ]:
df = df.apply(lambda x: x.str.strip() if x.dtype == 'object' else x)
df = df.apply(lambda x: x.str.strip() if x.dtype == 'category' else x)

# **Adding New Columns**

## **Shipping Delay**

In [ ]:
df['Shipping Delay'] = df.apply(lambda row: (row['Ship Date'] - row['Order Date']).days, axis=1)
df['Shipping Delay'] = df['Shipping Delay'].astype(int)
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,...,Discount,Profit,Order Priority,Shipping Cost,Customer Tenure,Marketing Channel,Product Rating,Return Status,Payment Method,Shipping Delay
0,CA-2016-101623,2016-02-28,2016-03-06,Standard Class,RR-19525,Rick Reed,CORPORATE,United States,New York City,New York,...,0.0,18.2400,Medium,5.45,Returning,Referral,1.0,No,Credit Card,7
1,CA-2017-154410,2017-10-21,2017-10-24,First Class,MD-17860,Michael Dominguez,Corporate,United States,Indianapolis,Indiana,...,0.0,9.0912,High,90.10,New,Social Media,4.0,No,Credit Card,3
2,CA-2017-127306,2017-01-14,2017-01-18,Standard Class,BH-11710,Brosina Hoffman,consumer,United States,Johnson City,Tennessee,...,0.7,-1.8392,High,0.27,New,Referral,4.0,Yes,Net Banking,4
3,CA-2016-126102,2016-09-10,2016-09-12,Second Class,DV-13465,Dianna Vittorini,consumer,United States,Los Angeles,California,...,0.2,89.9548,Low,19.00,Returning,Direct,1.0,No,Credit Card,2
4,CA-2016-101336,2016-11-13,2016-11-18,Standard Class,CK-12760,Cyma Kinney,Corporate,United States,New York City,New York,...,0.0,9.8901,Low,4.76,Returning,Ads,2.0,No,UPI,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60553,CA-2017-108287,2017-12-18,2017-12-20,First Class,AG-10330,Alex Grayson,CONSUMER,United States,Charlotte,North Carolina,...,0.2,1.4256,High,1.08,Returning,Social Media,3.0,No,UPI,2
61371,CA-2015-153073,2015-11-13,2015-11-13,Same Day,HA-14905,Helen Abelman,CONSUMER,United States,Chicago,Illinois,...,0.6,-7.4358,Critical,2.15,Returning,Referral,4.0,No,Cash on Delivery,0
61863,US-2016-164189,2016-03-24,2016-03-28,Standard Class,DR-12880,Dan Reichenbach,Corporate,United States,Gresham,Oregon,...,0.2,25.1980,Critical,41.59,Returning,Ads,3.0,No,Net Banking,4
64212,CA-2016-127698,2016-12-01,2016-12-01,Same Day,MV-18190,Mike Vittorini,Consumer,United States,Raleigh,North Carolina,...,0.2,86.3928,Medium,123.31,Returning,Referral,2.0,Yes,UPI,0
68988,CA-2015-118423,2015-03-24,2015-03-27,First Class,DP-13390,Dennis Pardue,home office,United States,Peoria,Illinois,...,0.3,-35.9058,Low,33.39,New,Social Media,5.0,No,Credit Card,3

### **Profit Margin**

In [ ]:
df['Profit Margin'] = df.apply(lambda row: (row['Profit'] / row['Sales']) * 100, axis=1)
df['Profit Margin'] = df['Profit Margin'].astype(float)
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,...,Profit,Order Priority,Shipping Cost,Customer Tenure,Marketing Channel,Product Rating,Return Status,Payment Method,Shipping Delay,Profit Margin
0,CA-2016-101623,2016-02-28,2016-03-06,Standard Class,RR-19525,Rick Reed,CORPORATE,United States,New York City,New York,...,18.2400,Medium,5.45,Returning,Referral,1.0,No,Credit Card,7,50.000000
1,CA-2017-154410,2017-10-21,2017-10-24,First Class,MD-17860,Michael Dominguez,Corporate,United States,Indianapolis,Indiana,...,9.0912,High,90.10,New,Social Media,4.0,No,Credit Card,3,1.000000
2,CA-2017-127306,2017-01-14,2017-01-18,Standard Class,BH-11710,Brosina Hoffman,consumer,United States,Johnson City,Tennessee,...,-1.8392,High,0.27,New,Referral,4.0,Yes,Net Banking,4,-73.333333
3,CA-2016-126102,2016-09-10,2016-09-12,Second Class,DV-13465,Dianna Vittorini,consumer,United States,Los Angeles,California,...,89.9548,Low,19.00,Returning,Direct,1.0,No,Credit Card,2,32.500000
4,CA-2016-101336,2016-11-13,2016-11-18,Standard Class,CK-12760,Cyma Kinney,Corporate,United States,New York City,New York,...,9.8901,Low,4.76,Returning,Ads,2.0,No,UPI,5,27.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60553,CA-2017-108287,2017-12-18,2017-12-20,First Class,AG-10330,Alex Grayson,CONSUMER,United States,Charlotte,North Carolina,...,1.4256,High,1.08,Returning,Social Media,3.0,No,UPI,2,11.250000
61371,CA-2015-153073,2015-11-13,2015-11-13,Same Day,HA-14905,Helen Abelman,CONSUMER,United States,Chicago,Illinois,...,-7.4358,Critical,2.15,Returning,Referral,4.0,No,Cash on Delivery,0,-42.500000
61863,US-2016-164189,2016-03-24,2016-03-28,Standard Class,DR-12880,Dan Reichenbach,Corporate,United States,Gresham,Oregon,...,25.1980,Critical,41.59,Returning,Ads,3.0,No,Net Banking,4,6.250000
64212,CA-2016-127698,2016-12-01,2016-12-01,Same Day,MV-18190,Mike Vittorini,Consumer,United States,Raleigh,North Carolina,...,86.3928,Medium,123.31,Returning,Referral,2.0,Yes,UPI,0,10.000000
68988,CA-2015-118423,2015-03-24,2015-03-27,First Class,DP-13390,Dennis Pardue,home office,United States,Peoria,Illinois,...,-35.9058,Low,33.39,New,Social Media,5.0,No,Credit Card,3,-10.000000

In [ ]:
df.columns = df.columns.str.strip().str.replace(r'\s','_',regex=True)

In [ ]:
df['Segment'] = df['Segment'].str.strip().str.title()
df['Segment']

0          Corporate
1          Corporate
2           Consumer
3           Consumer
4          Corporate
            ...
60553       Consumer
61371       Consumer
61863      Corporate
64212       Consumer
68988    Home Office
Name: Segment, Length: 5008, dtype: object

In [ ]:
df['Segment'].unique()

array(['Corporate', 'Consumer', 'Home Office'], dtype=object)

In [ ]:
df['Payment_Method'] = df['Payment_Method'].str.strip().str.title()
df['Payment_Method']

0             Credit Card
1             Credit Card
2             Net Banking
3             Credit Card
4                     Upi
               ...
60553                 Upi
61371    Cash On Delivery
61863         Net Banking
64212                 Upi
68988         Credit Card
Name: Payment_Method, Length: 5008, dtype: object

In [ ]:
df['Payment_Method'].unique()

array(['Credit Card', 'Net Banking', 'Upi', 'Cash On Delivery'],
      dtype=object)

In [ ]:
df.columns.str.title()

Index(['Order_Id', 'Order_Date', 'Ship_Date', 'Ship_Mode', 'Customer_Id',
       'Customer_Name', 'Segment', 'Country', 'City', 'State', 'Postal_Code',
       'Region', 'Product_Id', 'Category', 'Sub-Category', 'Product_Name',
       'Sales', 'Quantity', 'Discount', 'Profit', 'Order_Priority',
       'Shipping_Cost', 'Customer_Tenure', 'Marketing_Channel',
       'Product_Rating', 'Return_Status', 'Payment_Method', 'Shipping_Delay',
       'Profit_Margin'],
      dtype='object')

In [ ]:
df.rename(columns={'Sub-Category': 'Sub_Category'}, inplace=True)

In [ ]:
df['Country'].unique()

array(['United States'], dtype=object)

In [ ]:
df['Marketing_Channel'].unique()

array(['Referral', 'Social Media', 'Direct', 'Ads', 'Email', 'Unknown'],
      dtype=object)

In [ ]:
df['Order_ID'].value_counts()[df['Order_ID'].value_counts() > 1]

Series([], Name: count, dtype: int64)

In [ ]:
def Discount_Reason(Discount) :
                              if Discount == 0:
                                return 'No Discount'
                              elif Discount <=0.2:
                                return 'Promo'
                              elif Discount <= 0.4:
                                return 'Bulk Deal'
                              else:
                                return 'Clearance'

df['Discount_Reason'] = df['Discount'].apply(Discount_Reason)
df['Discount_Reason']

0        No Discount
1        No Discount
2          Clearance
3              Promo
4        No Discount
            ...
60553          Promo
61371      Clearance
61863          Promo
64212          Promo
68988      Bulk Deal
Name: Discount_Reason, Length: 5008, dtype: object

In [ ]:
df['Discount_Reason'] = df['Discount_Reason'].astype('category')

In [ ]:
df.to_csv('Supermarket_Sales.csv', index=False, encoding='utf-8', quoting=1)

In [ ]:
Order_info_Column =['Order_ID','Order_Date','Order_Priority','Ship_Date','Shipping_Delay','Ship_Mode','Shipping_Cost']
Product_info_Column =['Order_ID','Product_ID','Product_Name','Category','Sub_Category','Product_Rating','Marketing_Channel','Quantity','Return_Status','Discount','Sales','Profit','Profit_Margin','Discount_Reason']
Customer_info_Column = ['Order_ID','Customer_ID','Customer_Name','Segment','Customer_Tenure','Payment_Method','Country','State','City','Postal_Code','Region']

Convert as a dataframe

In [ ]:
Order_info = df[Order_info_Column]
Product_info = df[Product_info_Column]
Customer_info = df[Customer_info_Column]

Export as a Separate CSV Files

In [ ]:
Order_info.to_csv('Order_info.csv', index=False, encoding='utf-8', quoting=1)
Product_info.to_csv('Product_info.csv', index=False, encoding='utf-8', quoting=1)
Customer_info.to_csv('Customer_info.csv', index=False, encoding='utf-8', quoting=1)